#logging:
#  level:
#    com:
#      spring:
#        boot:
#          course:
#            SpringBootCourseApplication: debug
## we can off the specific package logs if you have a vast confusion
spring:
  data:
    redis:
      url: redis://default:8H3Z4IOhH6tmfVh0355Vt6W7HGIioC18@redis-15001.c264.ap-south-1-1.ec2.redns.redis-cloud.com:15001
