#logging:
#  level:
#    com:
#      spring:
#        boot:
#          course:
#            SpringBootCourseApplication: debug
## we can off the specific package logs if you have a vast confusion
spring:
  data:
    redis:
      url: your url
