#logging:
#  level:
#    com:
#      spring:
#        boot:
#          course:
#            SpringBootCourseApplication: debug
## we can off the specific package logs if you have a vast confusion
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  data:
    redis:
      url: ${REDIS_URI}
#      url: ${REDIS_URI}  # place holders

  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: weekly-sentiment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.spring.boot.course.journalapp.*
      client-id: ${KAFKA_CLIENT_ID}
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='X' password='X';
      session:
        timeout:
          ms: 45000

#springdoc:
#  swagger-ui:
#    enabled: true
#    path: /docs
#  packages-to-scan: com.spring.boot.course.journalapp.controller
#  show-actuator: true
