###
GET http://localhost:8082/journals/getAllJournalEntries

###
POST http://localhost:8082/journals/saveJournalEntry/prabhakar
Content-Type: application/json

{
  "title": "Athul",
  "description": "nirmal",
  "author": "prabhakar"
}

###
PUT http://localhost:8082/journals/updateJournalEntry
Content-Type: application/json

{
  "id": "6fc2c7f5-75ae-4e85-865b-76282094c88c",
  "title": "6fc2c7f5-75ae-4e85-865b-76282094c88c",
  "description": "6fc2c7f5-75ae-4e85-865b-76282094c88c",
  "author": "6fc2c7f5-75ae-4e85-865b-76282094c88c"
}


###
GET http://localhost:8082/journals/getJournalEntryById/6fc2c7f5-75ae-4e85-865b-76282094c88c

###
DELETE http://localhost:8082/journals/deleteById/734d2b86-6b18-4743-8bbb-cbcf323c85df

###
DELETE http://localhost:8082/journals/deleteJournalEntryById/prabhakar/4aa8d859-b789-4f0c-9bc7-73ccb14a8067

###
GET http://localhost:8082/journals/getJournalEntriesByUser/prabhakar
