###
GET http://localhost:8082/users/getAllUsers

###
POST http://localhost:8082/users/createUser
Content-Type: application/json

{
  "userName": "prabhakar",
  "email": "prabhakar@gmail.com",
  "sentimentAnalysis": false,
  "password": "prabha225",
  "roles": ["USER"]
}

###
PUT http://localhost:8082/users/updateUser/prabhakar
Content-Type: application/json

{
  "userName": "prabhakar",
  "password": "prabha12345"
}

###
DELETE http://localhost:8082/users/deleteById/8fc37d0f-c68e-4475-8e59-d4dcdd6956c2

###
GET http://localhost:8082/users/getUserByUserName/prabhakar
